version: "3.8"
services:
    redis1:
      image: bitnami/redis:7.0.10
      ports:
        - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_MAXMEMORY_POLICYallkeys=lru  
    redis2:
      image: bitnami/redis:7.0.10
      ports: 
        - "6380:6380"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_MAXMEMORY_POLICYallkeys=lru 
    redis3:
      image: bitnami/redis:7.0.10
      ports:
        - "6381:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_MAXMEMORY_POLICYallkeys=lru        
